version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=develop
      - DATABASE_URL=postgres://admin:qwerty123@host.docker.internal:32768/postgres
      - JWT_SECRET=your-secret-key
    extra_hosts:
      - "host.docker.internal:host-gateway"