-- Seed specification templates and options from category-specs.ts
-- Generated by scripts/generate-specs-migration.ts

-- Specifications for category: electronics (id: 1)
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (1, 1, 'brand', 'Бренд', 'text', true, 'Apple, Samsung, Xiaomi');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (2, 1, 'model', 'Модель', 'text', true, 'iPhone 14 Pro');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (3, 1, 'condition', 'Состояние', 'select', true, NULL);
-- Options for template 3
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (1, 3, 'Новый', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (2, 3, 'Б/у', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (3, 3, 'На запчасти', 2);
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (4, 1, 'color', 'Цвет', 'text', false, 'Черный, Белый, Синий');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (5, 1, 'weight', 'Вес (г)', 'number', false, '200');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (6, 1, 'country', 'Страна производитель', 'text', false, 'Китай, США, Корея');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (7, 1, 'warranty', 'Гарантия', 'select', false, NULL);
-- Options for template 7
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (4, 7, 'Есть', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (5, 7, 'Нет', 1);

-- Specifications for category: cars (id: 3)
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (8, 3, 'brand', 'Марка', 'text', true, 'Toyota, BMW, Mercedes');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (9, 3, 'model', 'Модель', 'text', true, 'Camry, X5, C-Class');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (10, 3, 'year', 'Год выпуска', 'number', true, '2020');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (11, 3, 'mileage', 'Пробег (км)', 'number', true, '50000');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (12, 3, 'engine', 'Двигатель', 'text', false, '2.0L, 3.0L Turbo');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (13, 3, 'transmission', 'Коробка передач', 'select', false, NULL);
-- Options for template 13
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (6, 13, 'Автомат', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (7, 13, 'Механика', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (8, 13, 'Робот', 2);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (9, 13, 'Вариатор', 3);
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (14, 3, 'fuel', 'Топливо', 'select', false, NULL);
-- Options for template 14
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (10, 14, 'Бензин', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (11, 14, 'Дизель', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (12, 14, 'Электричество', 2);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (13, 14, 'Гибрид', 3);
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (15, 3, 'color', 'Цвет', 'text', false, 'Черный, Белый, Красный');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (16, 3, 'vin', 'VIN номер', 'text', false, 'ABCDE1234567890');

-- Specifications for category: work (id: 4)
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (17, 4, 'position', 'Должность', 'text', true, 'Разработчик, Менеджер, Дизайнер');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (18, 4, 'experience', 'Требуемый опыт', 'select', false, NULL);
-- Options for template 18
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (14, 18, 'Без опыта', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (15, 18, '1-3 года', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (16, 18, '3-5 лет', 2);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (17, 18, '5+ лет', 3);
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (19, 4, 'employment', 'Тип занятости', 'select', false, NULL);
-- Options for template 19
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (18, 19, 'Полная', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (19, 19, 'Частичная', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (20, 19, 'Удаленная', 2);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (21, 19, 'Проектная', 3);
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (20, 4, 'salary', 'Зарплата ($)', 'number', false, '2000');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (21, 4, 'schedule', 'График работы', 'text', false, '5/2, сменный, гибкий');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (22, 4, 'education', 'Образование', 'select', false, NULL);
-- Options for template 22
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (22, 22, 'Не требуется', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (23, 22, 'Среднее', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (24, 22, 'Высшее', 2);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (25, 22, 'Магистратура', 3);
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (23, 4, 'skills', 'Ключевые навыки', 'text', false, 'JavaScript, React, Python');

-- Specifications for category: clothing (id: 5)
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (24, 5, 'brand', 'Бренд', 'text', false, 'Nike, Zara, H&M');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (25, 5, 'size', 'Размер', 'text', true, 'M, L, XL, 42, 44');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (26, 5, 'color', 'Цвет', 'text', true, 'Черный, Белый, Синий');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (27, 5, 'material', 'Материал', 'text', false, 'Хлопок, Шерсть, Синтетика');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (28, 5, 'condition', 'Состояние', 'select', true, NULL);
-- Options for template 28
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (26, 28, 'Новый', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (27, 28, 'Б/у отличное', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (28, 28, 'Б/у хорошее', 2);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (29, 28, 'На запчасти', 3);
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (29, 5, 'season', 'Сезон', 'select', false, NULL);
-- Options for template 29
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (30, 29, 'Лето', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (31, 29, 'Зима', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (32, 29, 'Демисезон', 2);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (33, 29, 'Всесезонный', 3);
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (30, 5, 'gender', 'Пол', 'select', false, NULL);
-- Options for template 30
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (34, 30, 'Мужской', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (35, 30, 'Женский', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (36, 30, 'Унисекс', 2);

-- Specifications for category: home (id: 6)
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (31, 6, 'type', 'Тип товара', 'text', true, 'Мебель, Техника, Текстиль');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (32, 6, 'brand', 'Бренд', 'text', false, 'IKEA, Bosch, Samsung');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (33, 6, 'material', 'Материал', 'text', false, 'Дерево, Металл, Пластик');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (34, 6, 'color', 'Цвет', 'text', false, 'Белый, Коричневый, Черный');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (35, 6, 'dimensions', 'Размеры (см)', 'text', false, '100x50x200');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (36, 6, 'weight', 'Вес (кг)', 'number', false, '15');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (37, 6, 'condition', 'Состояние', 'select', true, NULL);
-- Options for template 37
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (37, 37, 'Новый', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (38, 37, 'Б/у отличное', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (39, 37, 'Б/у хорошее', 2);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (40, 37, 'Требует ремонта', 3);
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (38, 6, 'warranty', 'Гарантия', 'select', false, NULL);
-- Options for template 38
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (41, 38, 'Есть', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (42, 38, 'Нет', 1);

-- Specifications for category: furniture (id: 2)
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (39, 2, 'type', 'Тип мебели', 'text', true, 'Диван, Стол, Стул, Шкаф');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (40, 2, 'brand', 'Бренд', 'text', false, 'IKEA, Ashley, Ethan Allen');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (41, 2, 'material', 'Материал', 'text', true, 'Дерево, Металл, Стекло, Кожа');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (42, 2, 'color', 'Цвет', 'text', true, 'Коричневый, Белый, Черный');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (43, 2, 'dimensions', 'Размеры (см)', 'text', true, '200x90x80');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (44, 2, 'weight', 'Вес (кг)', 'number', false, '50');
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (45, 2, 'style', 'Стиль', 'select', false, NULL);
-- Options for template 45
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (43, 45, 'Современный', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (44, 45, 'Классический', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (45, 45, 'Минимализм', 2);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (46, 45, 'Лофт', 3);
INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) VALUES (46, 2, 'condition', 'Состояние', 'select', true, NULL);
-- Options for template 46
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (47, 46, 'Новый', 0);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (48, 46, 'Б/у отличное', 1);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (49, 46, 'Б/у хорошее', 2);
INSERT INTO specification_options (id, template_id, value, sort_order) VALUES (50, 46, 'Требует ремонта', 3);
