/**
 * Script to generate SQL migration for specification templates and options
 * Reads from shared/category-specs.ts and generates INSERT statements
 */

import { categorySpecs } from '../shared/category-specs.js';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Map category slugs to category IDs (based on existing data in storage.ts)
const categorySlugToId: Record<string, number> = {
  electronics: 1,
  furniture: 2,
  cars: 3,
  work: 4,
  clothing: 5,
  home: 6,
};

function escapeSqlString(str: string): string {
  return str.replace(/'/g, "''");
}

function generateInsertStatements(): string {
  const lines: string[] = [];
  
  lines.push('-- Seed specification templates and options from category-specs.ts');
  lines.push('-- Generated by scripts/generate-specs-migration.ts');
  lines.push('');
  
  let templateId = 1;
  let optionId = 1;
  
  for (const [slug, specs] of Object.entries(categorySpecs)) {
    const categoryId = categorySlugToId[slug];
    if (!categoryId) {
      console.warn(`Warning: No category ID found for slug: ${slug}`);
      continue;
    }
    
    lines.push(`-- Specifications for category: ${slug} (id: ${categoryId})`);
    
    for (const spec of specs) {
      // Insert template
      const required = spec.required ? 'true' : 'false';
      const placeholder = spec.placeholder ? `'${escapeSqlString(spec.placeholder)}'` : 'NULL';
      
      lines.push(
        `INSERT INTO specification_templates (id, category_id, key, label, type, required, placeholder) ` +
        `VALUES (${templateId}, ${categoryId}, '${escapeSqlString(spec.key)}', '${escapeSqlString(spec.label)}', '${spec.type}', ${required}, ${placeholder});`
      );
      
      // Insert options for select type
      if (spec.type === 'select' && spec.options) {
        lines.push(`-- Options for template ${templateId}`);
        spec.options.forEach((option, index) => {
          lines.push(
            `INSERT INTO specification_options (id, template_id, value, sort_order) ` +
            `VALUES (${optionId}, ${templateId}, '${escapeSqlString(option)}', ${index});`
          );
          optionId++;
        });
      }
      
      templateId++;
    }
    
    lines.push('');
  }
  
  return lines.join('\n');
}

// Generate and write the migration file
const sqlContent = generateInsertStatements();
const outputPath = join(__dirname, '..', 'migrations', '0003_seed_spec_templates.sql');
writeFileSync(outputPath, sqlContent, 'utf-8');

// Count totals for logging
let totalTemplates = 0;
let totalOptions = 0;
for (const specs of Object.values(categorySpecs)) {
  totalTemplates += specs.length;
  for (const spec of specs) {
    if (spec.type === 'select' && spec.options) {
      totalOptions += spec.options.length;
    }
  }
}

console.log(`Generated SQL migration: ${outputPath}`);
console.log(`Total templates: ${totalTemplates}`);
console.log(`Total options: ${totalOptions}`);
